### ISSUE TITLE
Candidate phone number lookup is broken

### ISSUE THREAD

**Issue by crwallace** [colorofchange/call-power#8]
When I try to look up elected officials I get no result.

![screenshot 2017-08-04 18 28 49](https://user-images.githubusercontent.com/3453669/28989373-eab2f52c-7942-11e7-8bbb-1de949b28af9.png)

Also, when I test campaigns that previously were set up to use phone data from external sources, I hear, "sorry this campaign is not available in your area." I assume this means no number was found for my zipcode, but I think this is because the app cannot find any political contact data.

**Comment by bshyong** [comment]
Fixed! I loaded the new data and verified in the app

![screen shot 2017-08-05 at 8 54 21 pm](https://user-images.githubusercontent.com/303289/29000463-52594db0-7a20-11e7-9b45-3ba4047fbc9a.png)

**Comment by crwallace** [comment]
@bshyong -- I am still seeing an issue when I try to pull Governors by Name or by State:

By State:
![screenshot 2017-08-07 09 58 52](https://user-images.githubusercontent.com/3453669/29029885-33726dea-7b57-11e7-87b2-26a95501aedd.png)

By Name:
![screenshot 2017-08-07 09 58 24](https://user-images.githubusercontent.com/3453669/29029897-379fc962-7b57-11e7-9cb8-528729847c16.png)

**Comment by jlev** [comment]
I've addressed this in https://github.com/spacedogXYZ/call-power/issues/75
